language: node_js
node_js:
  - "10"
dist: trusty
services:
  - mysql 
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
cache:
  directories:
    - node_modules
before_install:
  - mysql -e 'CREATE DATABSE cs_project_ci;'
install:
  - npm install
  - npm run build
script:
  - npm run start
  - sleep 5
  - npm run test