pipeline {
    agent any

    tools {nodejs "node"}

    stages {
      stage("Dependencies") {
        steps {
          installDependencies()
        }
      }
      stage("Test") {
        steps {
          runTests()
        }
      }
      stage("Lint") {
        steps() {
          runLint()
        } 
      }
  }
}

frontend_project_dir = "v3"

def installDependencies() {
  sh "cd ${frontend_project_dir} && npm install"
}

def runTests() {
  sh "cd ${frontend_project_dir} && npm run tst"
}

def runLint() {
  sh "cd ${frontend_project_dir} && npm run lint"
}