pipeline {
    agent {
      docker { image 'angular/ngcontainer' }
    }

    tools {nodejs "node"}
    
    environment {
      FRONTEND_PROJECT_DIR = "v3"
    }

    stages {
      stage("Dependencies") {
        steps {
          installDependencies()
        }
      }
      stage("Test") {
        steps {
          runTests()
        }
      }
      stage("Lint") {
        steps() {
          runLint()
        } 
      }
  }
}

def installDependencies() {
  sh "cd ${FRONTEND_PROJECT_DIR} && npm install"
}

def runTests() {
  sh "cd ${FRONTEND_PROJECT_DIR} && npm run tst"
}

def runLint() {
  sh "cd ${FRONTEND_PROJECT_DIR} && npm run lint"
}