version: '3.4'

services:
  app:
    image: node:alpine
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - mysql
      - redis
    volumes:
      - ./../../:/app
    working_dir: /app
  mysql:
    container_name: mysql_host
    image: mysql:5.6
    environment:
      - MYSQL_DATABASE=cs_project
      - MYSQL_ROOT_PASSWORD=rower_cs
      - MYSQL_USER=rower
      - MYSQL_PASSWORD=rower
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    volumes:
      - "./../../data/mysql:/var/lib/mysql"
  redis:
    container_name: redis_host
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data: